### ISSUE TITLE
Hero page laggy on chrome 43.0.2357.134 m

### ISSUE THREAD

**Issue by LemonPi** [Shadowen/shadowen.github.io#7]
The animation constantly stutters when the view is panning around your living room
(are you moving the background image?)

**Comment by Shadowen** [comment]
It's a CSS animation. I think the stuttering is because the picture isn't high enough resolution (it's 1080). I might try uploading even higher resolution when I get a chance to, but I'm worried about loading times.

Of course I'm assuming you're on desktop. On mobile, it's probably your processor maxxing out or something. I will likely disable panning on mobile.
